In [1]:
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/ewenme/transfers/master/data/liga-nos.csv'
df=pd.read_csv(url)

In [2]:
#filtering only Benfica players
df = df[df['club_name'] == "SL Benfica"]

In [3]:
#filtering only sales from 2010
df=df[df['year'] >=2010]

In [4]:
#filtering only sold players
df=df[df['transfer_movement']=='out']

In [5]:
#only fee values corresponding to transfer amounts
df = df[df['fee'].str.contains('^€\d+\.?\d*[m|Th]$', regex=True)]

In [6]:
#removing unnecessary columns and correcting the value of fee_cleaned
df = df.drop(['season','transfer_movement','fee','league_name','country','club_name'],axis = 1)
df['fee_cleaned'] = df['fee_cleaned'] * 1000000

In [7]:
df.reset_index(drop=True)

,player_name,age,position,club_involved_name,transfer_period,fee_cleaned,year
0,Ángel Di María,22.0,Right Winger,Real Madrid,Summer,33000000.0,2010
1,Ramires,23.0,Central Midfield,Chelsea,Summer,22000000.0,2010
2,Rafik Halliche,23.0,Centre-Back,Fulham,Summer,2500000.0,2010
3,Ariza Makukula,29.0,Centre-Forward,Manisaspor,Summer,1700000.0,2010
4,David Luiz,23.0,Centre-Back,Chelsea,Winter,25000000.0,2010
...,...,...,...,...,...,...,...
86,Nuno Santos,23.0,Attacking Midfield,Charlotte,Summer,1000000.0,2022
87,Enzo Fernández,22.0,Central Midfield,Chelsea,Winter,121000000.0,2022
88,Diogo Gonçalves,25.0,Right Winger,FC Copenhagen,Winter,2000000.0,2022
89,Tomás Tavares,21.0,Right-Back,Spartak Moscow,Winter,2000000.0,2022
90,Gil Dias,26.0,Right Winger,VfB Stuttgart,Winter,1000000.0,2022

In [8]:
df.to_csv('historical sales.csv', index=False)